---
- hosts: Appservers
  become: true
  tasks:
  - name: Copy the war file
    copy: 
      src: target/hello.war
      dest: /opt/tomcat/webapps/
  - name: stop the tomcat
    shell: nohup /opt/tomcat/bin/shutdown.sh
  - name: starting the tomcat
    shell: nohup /opt/tomcat/bin/startup.sh  
